# Generated by Django 5.1.2 on 2024-11-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysterium', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
