# Generated by Django 5.1.2 on 2024-11-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysterium', '0006_comment_is_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_solved',
        ),
        migrations.AddField(
            model_name='post',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='solved_comment',
            field=models.ForeignKey(blank=True, help_text='The comment that solves this post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solved_posts', to='mysterium.comment'),
        ),
    ]
