# Generated by Django 5.1.2 on 2024-11-30 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysterium', '0009_post_can_be_disassembled_post_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dimensions',
        ),
    ]
