# Generated by Django 5.1.2 on 2024-12-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysterium', '0011_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='object_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/object_images/'),
        ),
    ]
