# Generated by Django 5.1.2 on 2024-12-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysterium', '0012_alter_post_object_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='object_image',
            field=models.ImageField(blank=True, null=True, upload_to='object_images/'),
        ),
    ]
