# Generated by Django 5.1.2 on 2024-12-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysterium', '0013_alter_post_object_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='object_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/object_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/user_images/'),
        ),
    ]
