# Generated by Django 5.1.2 on 2024-12-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysterium', '0015_alter_post_object_image_alter_post_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('kg', 'Kilogram'), ('g', 'Gram'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='length_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('kg', 'Kilogram'), ('g', 'Gram'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='price_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('kg', 'Kilogram'), ('g', 'Gram'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='weight_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('kg', 'Kilogram'), ('g', 'Gram'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='width_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('kg', 'Kilogram'), ('g', 'Gram'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='cm', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
