# Generated by Django 5.1.2 on 2024-12-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysterium', '0018_post_height_unit_post_length_unit_post_price_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='height_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('g', 'Gram'), ('kg', 'Kilogram'), ('USD', 'USD'), ('EUR', 'Euro'), ('TRY', 'TRY')], default='cm', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='length_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('g', 'Gram'), ('kg', 'Kilogram'), ('USD', 'USD'), ('EUR', 'Euro'), ('TRY', 'TRY')], default='cm', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='price_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('g', 'Gram'), ('kg', 'Kilogram'), ('USD', 'USD'), ('EUR', 'Euro'), ('TRY', 'TRY')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='weight_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('g', 'Gram'), ('kg', 'Kilogram'), ('USD', 'USD'), ('EUR', 'Euro'), ('TRY', 'TRY')], default='g', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='width_unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('m', 'Meter'), ('g', 'Gram'), ('kg', 'Kilogram'), ('USD', 'USD'), ('EUR', 'Euro'), ('TRY', 'TRY')], default='cm', max_length=10),
        ),
    ]
